/*
CREATE DATABASE bookstore;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS covers;
*/


CREATE TABLE covers (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(10) UNIQUE NOT NULL 
);

CREATE TABLE roles (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(10) UNIQUE NOT NULL 
);

CREATE TABLE books (
	id BIGSERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	author TEXT NOT NULL,
	isbn TEXT NOT NULL,
	pages SMALLINT,
	price DECIMAL (6, 2),
	cover_id BIGINT NOT NULL REFERENCES covers,
	deleted BOOLEAN NOT NULL DEFAULT FALSE
);




